services:
  db:
    image: postgres:18.3-alpine
    hostname: ${DATABASE_HOST}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - postgres_data_better_tasks:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=better-tasks

volumes:
  postgres_data_better_tasks:
