import { authQueryOptions } from "@/lib/auth/auth.queries"
import { LoginForm } from "@/lib/auth/components/login-form.tsx"
import { useSuspenseQuery } from "@tanstack/react-query"
import { createFileRoute, redirect } from "@tanstack/react-router"

/**
 * Home Page
 *
 * Shows different content based on authentication state:
 * - Not logged in: Login form with Sign In / Sign Up tabs
 * - Logged in: Dashboard with todos stats and quick actions
 */

// ===================================================================
// ROUTE
// ===================================================================
// This constant contains createFileRoute, is HOW whe have all this typeSafety around routes in our app. It's autogenerated on an "index.tsx" page with the correct route.
export const Route = createFileRoute("/")({
  // The parameters can be many. Here component says what do we render at this route, App is rendered in "/" in this case.
  component: HomePage,
  // Loader loads data on server & client. It tells WHAT data to load on the page.
  loader: async ({ context }) => {
    // Prefetch auth data
    const user = await context.queryClient.ensureQueryData(authQueryOptions())

    // If logged-in, redirect to todos page
    if (user) {
      throw redirect({ to: "/tasks" })
    }
  },
})

// ===================================================================
// HOME PAGE "/"
// ===================================================================
function HomePage() {
  // Get user from React Query cache
  const { data: user } = useSuspenseQuery(authQueryOptions())

  // If not logged in, show login form
  if (!user) {
    return <LoginForm variant="page" />
  }

  return <div>Public home / login</div>
}
