import {createFileRoute, Link} from '@tanstack/react-router'
import {db} from "@/db";
import {createClientOnlyFn, createIsomorphicFn, createServerFn, createServerOnlyFn} from "@tanstack/react-start";
import {Badge} from "src/components/ui/badge.tsx"
import {Button} from "@/components/ui/button.tsx";
import {ListTodoIcon, PlusIcon} from "lucide-react";
import {Empty, EmptyContent, EmptyDescription, EmptyHeader, EmptyMedia, EmptyTitle} from "@/components/ui/empty.tsx";

// Equivalent of Server Actions (NextJS). Main difference, now in Tanstack it works not only to POST data, but to GET data too.
// It will make a server action so the client can GET / POST the last datas.
// When it need to get the data, it makes a fetch request using GET method, and runs the code (db query) from the handler into the server.
// So it tells to the Browser :
//  - A) We are on the client -> Make a fetch request
//  - B) we are on the server -> Call the code (db query), with no changes at all.
const serverLoader = createServerFn({method: 'GET' }).handler(() => {
  return db.query.todos.findMany()
})

// Other functions for server / client :
//  createClientOnlyFn
//  createServerFn
//  createServerOnlyFn
// createIsomorphicFn : is like "createServerFn" but my own done manually
const isomorph = createIsomorphicFn().server(() => {
  console.log("On server")
}).client(() => {
  console.log("On client")
})

// This constant contains createFileRoute, is HOW whe have all this typeSafety around routes in our app. It's autogenerated on a "index.tsx" page with the correct route.
export const Route = createFileRoute('/')({
  // The parameters can be many. Here component says what do we render at this route, App is rendered in "/" in this case.
  component: App,
  // Loader loads data on server & client. It tells WHAT data to load on the page.
  loader:  () => {
    console.log("loading data")
    return serverLoader()
  }
})

function App() {
  // Hook that gets the data from the loader
  const data = Route.useLoaderData()

  const completedCount = data.filter( todo => todo.isCompleted).length
  const totalCount = data.length


  return (
      <div className="min-h-screen container space-y-8">
        <div className="flex justify-between items-center gap-4">
          {/* HEADER SECTION */}
          {/* Title of page and count of todos done */}
          <div className="space-y-2">
            <h1 className="text-4xl font-bold">
              Todo List
            </h1>
            {
              totalCount > 0 && (
                  <Badge variant="outline">
                    {completedCount} of {totalCount} completed
                  </Badge>
                )
            }
          </div>

          {/* Buttons section  to add a todo */}
          <div>
            <Button size="sm" asChild>
              <Link to={"/todos/new"}>
                <PlusIcon /> Add Todo
              </Link>
            </Button>
          </div>
        </div>

        {/* BODY SECTION */}
        {/* Table of todos */}
        <TodoListTable todos={data}/>
      </div>

  )
}

function TodoListTable({todos,} :
  {
    todos: Array<{
      id: string
      title: string
      isCompleted: boolean
      createdAt: Date
    }>
  })
{
  // 2 sections
  if(todos.length === 0){
    return (
        <Empty className="border border-dashed">
          <EmptyHeader>
            <EmptyMedia variant="icon">
              <ListTodoIcon/>

            </EmptyMedia>
            <EmptyTitle>No Todos</EmptyTitle>
            <EmptyDescription>
              Try Adding a new todo
            </EmptyDescription>
          </EmptyHeader>
          <EmptyContent>
            <Button asChild>
              <Link to={"/todos/new"}>
                <PlusIcon /> Add Todo
              </Link>
            </Button>
          </EmptyContent>
        </Empty>
    )
  }
}
