import {BetterAuthPlugin} from "better-auth";

/**
 * Custom User Fields Plugin
 *
 * This plugin defines additional fields for the user table.
 * Better Auth CLI will auto-generate the database schema.
 *
 * 4 Field options:
 * - type:      "string" | "number" | "boolean" | "date"
 * - required:  boolean (default: false) - if required on new record
 * - unique:    boolean (default: false) - if field should be unique
 * - input:     boolean (default: true)  - if user can set this field themselves
 *   !!! Set to false for sensitive fields like "role" to prevent users from self-assigning roles !!!
 *
 * Usage:
 * 1. Import in auth.ts: plugins: [customUserFieldsPlugin()]
 * 2. Run: npx @better-auth/cli generate
 * 3. Run: npx drizzle-kit push (or your migration command)
 */

export const tasksTablePlugin = () => {
    return {
        // id of the plugin in better auth only
        id: "tasks-tables",
        // Schema allows to group different models together
        schema: {
            tasksTable: {
                // Name of the Table in the DB
                modelName: "tasks",
                // id -> autogenerated by better-auth
                fields: {
                    userId: { type: "string", required: true, references: {model: "user", field: "id", onDelete: "cascade"} },
                    title: {type: "string", required: true},
                    created_at: {type: "date", required: true},
                    updated_at: {type: "date", required: true},
                }
            },
            todosTable: {
                // Name of the Table in the DB
                modelName: "todos",
                fields: {
                    taskId: {type: "string", required: true, references: {model: "tasks", field: "id", onDelete: "cascade"} },
                    content: {type: "string", required: true},
                    isCompleted: {type: "boolean",required: true},
                    sortPosition: {type: "number", required: true},
                    createdAt: {type: "date", required: true},
                    updatedAt: {type: "date", required: true},
                }
            }
        }
    } satisfies BetterAuthPlugin
}