/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as appAuthRouteRouteImport } from './routes/(app)/_auth/route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as publicAuthLoginIndexRouteImport } from './routes/(public)/auth/login/index'
import { Route as appAuthTodosIndexRouteImport } from './routes/(app)/_auth/todos/index'
import { Route as appAuthTasksIndexRouteImport } from './routes/(app)/_auth/tasks/index'
import { Route as appAuthTodosNewIndexRouteImport } from './routes/(app)/_auth/todos/new/index'
import { Route as appAuthTasksIdIndexRouteImport } from './routes/(app)/_auth/tasks/$id/index'
import { Route as appAuthTodosIdEditIndexRouteImport } from './routes/(app)/_auth/todos/$id/edit/index'

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const appAuthRouteRoute = appAuthRouteRouteImport.update({
  id: '/(app)/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const publicAuthLoginIndexRoute = publicAuthLoginIndexRouteImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => publicRouteRoute,
} as any)
const appAuthTodosIndexRoute = appAuthTodosIndexRouteImport.update({
  id: '/todos/',
  path: '/todos/',
  getParentRoute: () => appAuthRouteRoute,
} as any)
const appAuthTasksIndexRoute = appAuthTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => appAuthRouteRoute,
} as any)
const appAuthTodosNewIndexRoute = appAuthTodosNewIndexRouteImport.update({
  id: '/todos/new/',
  path: '/todos/new/',
  getParentRoute: () => appAuthRouteRoute,
} as any)
const appAuthTasksIdIndexRoute = appAuthTasksIdIndexRouteImport.update({
  id: '/tasks/$id/',
  path: '/tasks/$id/',
  getParentRoute: () => appAuthRouteRoute,
} as any)
const appAuthTodosIdEditIndexRoute = appAuthTodosIdEditIndexRouteImport.update({
  id: '/todos/$id/edit/',
  path: '/todos/$id/edit/',
  getParentRoute: () => appAuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/tasks/': typeof appAuthTasksIndexRoute
  '/todos/': typeof appAuthTodosIndexRoute
  '/auth/login/': typeof publicAuthLoginIndexRoute
  '/tasks/$id/': typeof appAuthTasksIdIndexRoute
  '/todos/new/': typeof appAuthTodosNewIndexRoute
  '/todos/$id/edit/': typeof appAuthTodosIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/tasks': typeof appAuthTasksIndexRoute
  '/todos': typeof appAuthTodosIndexRoute
  '/auth/login': typeof publicAuthLoginIndexRoute
  '/tasks/$id': typeof appAuthTasksIdIndexRoute
  '/todos/new': typeof appAuthTodosNewIndexRoute
  '/todos/$id/edit': typeof appAuthTodosIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(public)': typeof publicRouteRouteWithChildren
  '/(app)/_auth': typeof appAuthRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(app)/_auth/tasks/': typeof appAuthTasksIndexRoute
  '/(app)/_auth/todos/': typeof appAuthTodosIndexRoute
  '/(public)/auth/login/': typeof publicAuthLoginIndexRoute
  '/(app)/_auth/tasks/$id/': typeof appAuthTasksIdIndexRoute
  '/(app)/_auth/todos/new/': typeof appAuthTodosNewIndexRoute
  '/(app)/_auth/todos/$id/edit/': typeof appAuthTodosIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/auth/$'
    | '/tasks/'
    | '/todos/'
    | '/auth/login/'
    | '/tasks/$id/'
    | '/todos/new/'
    | '/todos/$id/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/auth/$'
    | '/tasks'
    | '/todos'
    | '/auth/login'
    | '/tasks/$id'
    | '/todos/new'
    | '/todos/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/(public)'
    | '/(app)/_auth'
    | '/api/auth/$'
    | '/(app)/_auth/tasks/'
    | '/(app)/_auth/todos/'
    | '/(public)/auth/login/'
    | '/(app)/_auth/tasks/$id/'
    | '/(app)/_auth/todos/new/'
    | '/(app)/_auth/todos/$id/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  publicRouteRoute: typeof publicRouteRouteWithChildren
  appAuthRouteRoute: typeof appAuthRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_auth': {
      id: '/(app)/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appAuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/auth/login/': {
      id: '/(public)/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof publicAuthLoginIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(app)/_auth/todos/': {
      id: '/(app)/_auth/todos/'
      path: '/todos'
      fullPath: '/todos/'
      preLoaderRoute: typeof appAuthTodosIndexRouteImport
      parentRoute: typeof appAuthRouteRoute
    }
    '/(app)/_auth/tasks/': {
      id: '/(app)/_auth/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof appAuthTasksIndexRouteImport
      parentRoute: typeof appAuthRouteRoute
    }
    '/(app)/_auth/todos/new/': {
      id: '/(app)/_auth/todos/new/'
      path: '/todos/new'
      fullPath: '/todos/new/'
      preLoaderRoute: typeof appAuthTodosNewIndexRouteImport
      parentRoute: typeof appAuthRouteRoute
    }
    '/(app)/_auth/tasks/$id/': {
      id: '/(app)/_auth/tasks/$id/'
      path: '/tasks/$id'
      fullPath: '/tasks/$id/'
      preLoaderRoute: typeof appAuthTasksIdIndexRouteImport
      parentRoute: typeof appAuthRouteRoute
    }
    '/(app)/_auth/todos/$id/edit/': {
      id: '/(app)/_auth/todos/$id/edit/'
      path: '/todos/$id/edit'
      fullPath: '/todos/$id/edit/'
      preLoaderRoute: typeof appAuthTodosIdEditIndexRouteImport
      parentRoute: typeof appAuthRouteRoute
    }
  }
}

interface publicRouteRouteChildren {
  publicAuthLoginIndexRoute: typeof publicAuthLoginIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicAuthLoginIndexRoute: publicAuthLoginIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

interface appAuthRouteRouteChildren {
  appAuthTasksIndexRoute: typeof appAuthTasksIndexRoute
  appAuthTodosIndexRoute: typeof appAuthTodosIndexRoute
  appAuthTasksIdIndexRoute: typeof appAuthTasksIdIndexRoute
  appAuthTodosNewIndexRoute: typeof appAuthTodosNewIndexRoute
  appAuthTodosIdEditIndexRoute: typeof appAuthTodosIdEditIndexRoute
}

const appAuthRouteRouteChildren: appAuthRouteRouteChildren = {
  appAuthTasksIndexRoute: appAuthTasksIndexRoute,
  appAuthTodosIndexRoute: appAuthTodosIndexRoute,
  appAuthTasksIdIndexRoute: appAuthTasksIdIndexRoute,
  appAuthTodosNewIndexRoute: appAuthTodosNewIndexRoute,
  appAuthTodosIdEditIndexRoute: appAuthTodosIdEditIndexRoute,
}

const appAuthRouteRouteWithChildren = appAuthRouteRoute._addFileChildren(
  appAuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  publicRouteRoute: publicRouteRouteWithChildren,
  appAuthRouteRoute: appAuthRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
